services:
  - type: web
    name: indiacart24-server
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
